---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "cert-manager"
  namespace: "cert-manager-policies"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    cert-manager: "true"
  sourceFiles:
    # Create operators policies that will be installed in all clusters
    - fileName: ./CertManagerSubscriptionNS.yaml
      policyName: "subscriptions-policy"
    - fileName: ./CertManagerSubscriptionOperGroup.yaml
      policyName: "subscriptions-policy"
    - fileName: ./CertManagerSubscription.yaml
      policyName: "subscriptions-policy"
    - fileName: ./CertManagerOperatorStatus.yaml
      policyName: "subscriptions-policy"
    - fileName: CertManagerNS.yaml
      policyName: "config-policy"
    - fileName: CertManagerClusterIssuer.yaml
      policyName: "config-policy"
    - fileName: CertManagerIngressCertificate.yaml
      policyName: "config-policy"
    - fileName: CertManagerIngressCertificateConfig.yaml
      policyName: "config-policy"
    - fileName: InternalCAChainConfigMap.yaml
      policyName: "config-policy"
    - fileName: CfsslInternalCAKeySecret.yaml
      policyName: "config-policy"
    - fileName: CfsslIssuerDeploymentPatch.yaml
      policyName: "config-policy"
    - fileName: CertManagerApiserverCertificate.yaml
      policyName: "config-policy"
      #- fileName: ReduceMonitoringFootprint.yaml
      #  policyName: "config-policy"
