apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
  annotations:
    workload.openshift.io/allowed: management
    ran.openshift.io/ztp-deploy-wave: "2"
    # openshift.io/cluster-monitoring: true
