apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  name: cert-manager-operators
  namespace: cert-manager-operator
spec:
  targetNamespaces:
  - cert-manager-operator
  upgradeStrategy: Default
