apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  labels:
    operators.coreos.com/openshift-cert-manager-operator.cert-manager-operator: ""
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
