---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    ran.openshift.io/ztp-deploy-wave: "40"
spec:
  servingCerts:
    namedCertificates:
    - names:
      - 'api.{{ (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain }}'
      servingCertificate:
        name: apiserver-tls-cert
